// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import { ExternalConnectors } from '@microsoft/microsoft-graph-types-beta';

export const issuesSchema: ExternalConnectors.Schema = {
  baseType: 'microsoft.graph.externalItem',
  properties: [
    {
      aliases: ['issueTitle'],
      name: 'title',
      type: 'string',
      isSearchable: true,
      isQueryable: true,
      isRetrievable: true,
      isRefinable: false,
      labels: ['title'],
    },
    {
      aliases: ['message'],
      name: 'body',
      type: 'string',
      isSearchable: true,
      isQueryable: true,
      isRetrievable: true,
      isRefinable: false,
    },

    {
      name: 'assignees',
      type: 'string',
      isSearchable: true,
      isQueryable: true,
      isRetrievable: true,
      isRefinable: false,
    },
    {
      name: 'labels',
      type: 'string',
      isSearchable: true,
      isQueryable: true,
      isRetrievable: true,
      isRefinable: false,
    },
    {
      name: 'state',
      type: 'string',
      isSearchable: false,
      isQueryable: true,
      isRetrievable: true,
      isRefinable: true,
    },
    {
      name: 'issueUrl',
      type: 'string',
      isSearchable: false,
      isQueryable: false,
      isRetrievable: true,
      isRefinable: false,
      labels: ['url'],
    },
    {
      name: 'icon',
      type: 'string',
      isSearchable: false,
      isQueryable: false,
      isRetrievable: true,
      isRefinable: false,
      labels: ['iconUrl'],
    },
    {
      name: 'updatedAt',
      type: 'dateTime',
      isSearchable: false,
      isQueryable: true,
      isRetrievable: true,
      isRefinable: true,
      labels: ['lastModifiedDateTime'],
    },
    {
      name: 'lastModifiedBy',
      type: 'string',
      isSearchable: true,
      isQueryable: true,
      isRetrievable: true,
      isRefinable: false,
      labels: ['lastModifiedBy'],
    },
  ],
};

export const reposSchema: ExternalConnectors.Schema = {
  baseType: 'microsoft.graph.externalItem',
  properties: [
    {
      aliases: ['repoName'],
      name: 'title',
      type: 'string',
      isSearchable: true,
      isQueryable: true,
      isRetrievable: true,
      isRefinable: false,
      labels: ['title'],
    },
    {
      name: 'description',
      type: 'string',
      isSearchable: true,
      isQueryable: true,
      isRetrievable: true,
      isRefinable: false,
    },

    {
      name: 'visibility',
      type: 'string',
      isSearchable: false,
      isQueryable: true,
      isRetrievable: true,
      isRefinable: true,
    },
    {
      name: 'createdBy',
      type: 'string',
      isSearchable: true,
      isQueryable: true,
      isRetrievable: true,
      isRefinable: false,
      labels: ['createdBy'],
    },
    {
      name: 'repoUrl',
      type: 'string',
      isSearchable: true,
      isQueryable: false,
      isRetrievable: true,
      isRefinable: false,
      labels: ['url'],
    },
    {
      name: 'icon',
      type: 'string',
      isSearchable: false,
      isQueryable: false,
      isRetrievable: true,
      isRefinable: false,
      labels: ['iconUrl'],
    },
    {
      name: 'updatedAt',
      type: 'dateTime',
      isSearchable: false,
      isQueryable: true,
      isRetrievable: true,
      isRefinable: true,
      labels: ['lastModifiedDateTime'],
    },
    {
      name: 'lastModifiedBy',
      type: 'string',
      isSearchable: true,
      isQueryable: true,
      isRetrievable: true,
      isRefinable: false,
      labels: ['lastModifiedBy'],
    },
    {
      name: 'userUrl',
      type: 'string',
      isSearchable: true,
      isQueryable: false,
      isRetrievable: true,
      isRefinable: false,
    },
  ],
};
